import { useEffect, useRef, useState } from "react";
import { getCameras, getVideos, recommendNextAction, reprocessVideo, setTrainingDataset, uploadVideo } from "../api/client";
import StatusBadge from "../components/StatusBadge";

const signals = { plate_match: .76, appearance_match: .81, color_match: .72, direction_match: .85, travel_time_match: .78 };

function Intake({ cameras, reload }) {
  const [camera, setCamera] = useState("CAM-01"), [file, setFile] = useState(null), [training, setTraining] = useState(false), [busy, setBusy] = useState(false), [note, setNote] = useState(""), [recording, setRecording] = useState(false);
  const picker = useRef(), recorder = useRef(), chunks = useRef([]);
  const send = async (chosen = file) => {
    if (!chosen) return setNote("Choose or record a video first.");
    setBusy(true); const form = new FormData(); form.append("file", chosen, chosen.name || "recording.webm"); form.append("camera_id", camera); form.append("include_in_training_dataset", training);
    try { await uploadVideo(form); setFile(null); picker.current.value = ""; setNote("Accepted — OpenCV processing has started."); reload(); } catch (e) { setNote(e.response?.data?.detail || "Upload failed. Confirm the backend is running."); } finally { setBusy(false); }
  };
  const record = async () => {
    if (recording) return recorder.current?.stop();
    try { const stream = await navigator.mediaDevices.getUserMedia({ video: true, audio: false }); chunks.current = []; const rec = new MediaRecorder(stream, { mimeType: MediaRecorder.isTypeSupported("video/webm") ? "video/webm" : undefined }); rec.ondataavailable = e => e.data.size && chunks.current.push(e.data); rec.onstop = () => { stream.getTracks().forEach(t => t.stop()); setRecording(false); send(new File([new Blob(chunks.current, { type: "video/webm" })], `recording-${Date.now()}.webm`, { type: "video/webm" })); }; recorder.current = rec; rec.start(); setRecording(true); setNote("Recording in progress. Press stop when complete."); } catch { setNote("Camera access was not granted. Use Upload recorded video instead."); }
  };
  return <section className="rounded-xl border border-console-line bg-console-panel p-5"><div className="mb-5 flex justify-between"><div><p className="font-mono text-[11px] uppercase tracking-wider text-console-accent">Video intake</p><h2 className="mt-1 text-lg font-semibold">Add a camera feed</h2></div><span className="rounded bg-console-accent/10 px-2 py-1 font-mono text-[10px] text-console-accent">OPEN-CV</span></div><label className="block text-sm text-console-muted">Camera ID<select value={camera} onChange={e => setCamera(e.target.value)} className="mt-1 w-full rounded border border-console-line bg-console-bg p-2.5 text-console-text">{cameras.map(c => <option key={c.camera_id} value={c.camera_id}>{c.camera_id} — {c.label}</option>)}</select></label><input ref={picker} type="file" accept="video/*" className="hidden" onChange={e => setFile(e.target.files?.[0] || null)} /><button onClick={() => picker.current.click()} className="mt-4 w-full rounded border border-dashed border-console-muted/60 bg-console-bg/50 p-3 text-sm hover:border-console-accent">↑ Upload recorded video</button>{file && <p className="mt-2 truncate text-xs text-console-accent">Ready: {file.name}</p>}<div className="mt-3 grid grid-cols-2 gap-2"><button onClick={() => send()} disabled={busy || recording} className="rounded bg-console-accent p-2.5 text-sm font-semibold text-console-bg disabled:opacity-50">{busy ? "Uploading…" : "Process video"}</button><button onClick={record} disabled={busy} className={`rounded border p-2.5 text-sm ${recording ? "border-console-alert text-console-alert" : "border-console-line"}`}>{recording ? "■ Stop recording" : "● Record here"}</button></div><label className="mt-4 flex gap-2 text-xs leading-5 text-console-muted"><input type="checkbox" checked={training} onChange={e => setTraining(e.target.checked)} className="mt-1 accent-console-accent" />Keep this as future training data. It is stored for later labeling; it does not train a model automatically.</label>{note && <p className="mt-3 rounded bg-console-bg p-2.5 text-xs text-console-muted">{note}</p>}</section>;
}

function Library({ videos, reload }) {
  return <section className="mt-6"><div className="mb-4 flex items-end justify-between"><div><p className="font-mono text-[11px] uppercase tracking-wider text-console-accent">Local case library</p><h2 className="mt-1 text-lg font-semibold">Uploaded camera feeds</h2></div><button onClick={reload} className="text-sm text-console-accent">Refresh</button></div>{videos.length ? <div className="space-y-3">{videos.map(v => <article key={v.id} className="rounded-xl border border-console-line bg-console-panel p-4"><div className="flex flex-wrap justify-between gap-2"><div><b>{v.original_name}</b><p className="mt-1 font-mono text-[11px] text-console-muted">{v.camera_id} · {v.metadata.width}×{v.metadata.height} · {v.metadata.fps} fps</p></div><span className={`h-fit rounded px-2 py-1 font-mono text-[10px] uppercase ${v.status === "complete" ? "bg-console-accent/10 text-console-accent" : v.status === "failed" ? "bg-console-alert/10 text-console-alert" : "bg-console-warn/10 text-console-warn"}`}>{v.status}</span></div><div className="mt-3 flex flex-wrap items-center gap-3 text-xs text-console-muted"><span>{v.event_count || 0} motion events</span>{v.error && <span className="text-console-alert">{v.error}</span>}<button onClick={() => reprocessVideo(v.id).then(reload)} className="text-console-accent">Reprocess</button><label><input type="checkbox" checked={v.training_dataset} onChange={e => setTrainingDataset(v.id, e.target.checked).then(reload)} className="mr-1 accent-console-accent" />training dataset</label></div></article>)}</div> : <div className="rounded-xl border border-dashed border-console-line p-6 text-center text-sm text-console-muted">No videos yet. Upload one to start processing real frames.</div>}</section>;
}

export default function Dashboard() {
  const [cameras, setCameras] = useState([]), [videos, setVideos] = useState([]), [result, setResult] = useState(null), [error, setError] = useState(""), [running, setRunning] = useState(false);
  const reload = async () => { try { const [c, v] = await Promise.all([getCameras(), getVideos()]); setCameras(c.cameras); setVideos(v.videos); setError(""); } catch { setError("Backend unavailable. Start FastAPI on port 8000, then refresh."); } };
  useEffect(() => { reload(); const id = setInterval(reload, 5000); return () => clearInterval(id); }, []);
  const investigate = async () => { setRunning(true); try { setResult(await recommendNextAction({ case_id: "DEMO-CASE-001", last_known_camera: cameras[0]?.camera_id || "CAM-01", elapsed_seconds: 180, direction_hint: "north", ...signals })); } catch { setError("Investigation request failed."); } finally { setRunning(false); } };
  const cameraList = cameras.length ? cameras : [{ camera_id: "CAM-01", label: "Camera 01" }];
  return <main className="mx-auto min-h-screen max-w-6xl p-5 md:p-9"><header className="mb-8 flex flex-wrap items-start justify-between gap-4 border-b border-console-line pb-5"><div><p className="mb-2 font-mono text-xs tracking-[.22em] text-console-accent">PHOENIX / SIH26127</p><h1 className="text-2xl font-semibold tracking-tight md:text-3xl">Autonomous Investigation Console</h1><p className="mt-2 max-w-2xl text-sm text-console-muted">Your uploaded traffic videos are simulated camera feeds. Phoenix reads real frames and preserves real motion evidence.</p></div><StatusBadge /></header>{error && <div className="mb-5 rounded border border-console-alert/30 bg-console-alert/10 p-3 text-sm text-console-alert">{error}</div>}<div className="grid gap-5 lg:grid-cols-[.82fr_1.18fr]"><Intake cameras={cameraList} reload={reload}/><section className="rounded-xl border border-console-line bg-console-panel p-5"><div className="mb-5 flex items-start justify-between"><div><p className="font-mono text-[11px] uppercase tracking-wider text-console-accent">Decision support</p><h2 className="mt-1 text-lg font-semibold">Investigation Path Planner</h2></div><button onClick={investigate} disabled={running} className="rounded bg-console-accent px-3 py-2 text-sm font-semibold text-console-bg disabled:opacity-50">{running ? "Reasoning…" : "Run recommendation"}</button></div>{result ? <div><p className="mb-3 rounded bg-console-bg p-3 text-sm">Status: <b className="capitalize text-console-accent">{result.status.replace("_", " ")}</b> · fused confidence <b>{Math.round(result.evidence.fused_confidence * 100)}%</b></p>{result.ranked_cameras.map(c => <div key={c.camera_id} className="mb-2 rounded border border-console-line p-3"><b className="font-mono text-console-accent">#{c.rank} {c.camera_id} · {Math.round(c.confidence * 100)}%</b><p className="mt-1 text-xs text-console-muted">{c.reasons.join(" · ")}</p></div>)}</div> : <p className="text-sm leading-6 text-console-muted">Run the deterministic evidence-fusion and graph planner. It returns “insufficient evidence” when confidence is below the safety threshold.</p>}</section></div><Library videos={videos} reload={reload}/><footer className="mt-10 border-t border-console-line pt-5 text-xs leading-5 text-console-muted">Prototype scope: detection uses real OpenCV motion analysis. It does not yet read number plates, identify a vehicle, or train a model. Footage marked as training data is only retained for a later labelled-training workflow.</footer></main>;
}
