"""
Vision Agent — now wired to REAL video ingestion + motion detection.

Current real pipeline per frame:
  video file --> VideoFileIngestService (real OpenCV frame reads)
             --> MotionBlobDetector (real background-subtraction detection)
             --> dominant_color estimate (real pixel sampling)
             --> structured event dict (matches VEHICLE_EVENTS schema)

Still placeholder, clearly labeled where so:
  - vehicle_type: not yet classified (needs YOLO) -> returned as "unknown"
  - plate_text / plate_confidence: not yet extracted (needs ANPR/OCR) -> None
  - direction: estimated crudely from horizontal centroid movement across
    consecutive frames - a real but simple signal, not invented.

This keeps the output contract EXACTLY the same shape whether it's the
motion detector or a future YOLO model producing it, so nothing downstream
(API routes, Investigation Agent, frontend) needs to change later.
"""
from __future__ import annotations

from datetime import datetime, timezone
from typing import Optional

from app.cv.detection import Detection, MotionBlobDetector
from app.services.video_ingest import VideoFileIngestService


class VisionAgent:
    def __init__(self) -> None:
        self._detector = MotionBlobDetector()

    def process_video_file(
        self,
        video_path: str,
        camera_id: str,
        sample_every_n_frames: int = 2,
        max_frames: Optional[int] = None,
    ) -> list[dict]:
        """
        Runs the real detection pipeline against an actual video file and
        returns structured vehicle events. Works on any video file, including
        the synthetic placeholder generated by scripts/generate_synthetic_video.py.
        """
        ingest = VideoFileIngestService(video_path=video_path, camera_id=camera_id)
        events: list[dict] = []
        previous_centroid_x: Optional[float] = None

        for frame_data in ingest.frames(sample_every_n_frames=sample_every_n_frames):
            if max_frames is not None and frame_data.frame_index >= max_frames:
                break

            detections: list[Detection] = self._detector.detect(frame_data.image)

            for det in detections:
                centroid_x = det.x + det.w / 2
                direction = "unknown"
                if previous_centroid_x is not None:
                    direction = "east" if centroid_x > previous_centroid_x else "west"
                previous_centroid_x = centroid_x

                color = self._detector.dominant_color(frame_data.image, det)

                events.append(
                    {
                        "vehicle_id": None,  # not yet resolved - needs Trajectory Agent matching
                        "camera_id": camera_id,
                        "event_timestamp": datetime.now(timezone.utc).isoformat(),
                        "plate_text": None,  # placeholder - ANPR not wired in yet
                        "plate_confidence": None,
                        "vehicle_type": "unknown",  # placeholder - classification not wired in yet
                        "color": color,
                        "direction": direction,
                        "bounding_box": {"x": det.x, "y": det.y, "w": det.w, "h": det.h},
                        "frame_index": frame_data.frame_index,
                        "source": "motion_detector_real_video",
                    }
                )

        return events

    def get_mock_events(self, camera_id: str) -> list[dict]:
        """Deterministic mock event for frontend/API development when no
        video file is available at all. Clearly labeled source: 'mock'."""
        return [
            {
                "vehicle_id": "MOCK-VEH-001",
                "camera_id": camera_id,
                "event_timestamp": datetime.now(timezone.utc).isoformat(),
                "plate_text": "RJ14AB1234",
                "plate_confidence": 0.75,
                "vehicle_type": "motorcycle",
                "color": "black",
                "direction": "north",
                "source": "mock",
            }
        ]
